# Enterprise Flutter App Analysis Options
# This file configures static analysis for enterprise-level Flutter development

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Enterprise-specific overrides
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_final_fields: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    
    # Security-focused rules
    avoid_web_libraries_in_flutter: true
    avoid_slow_async_io: true
    
    # Code quality rules
    exhaustive_cases: true
    parameter_assignments: true
    prefer_asserts_with_message: true
    public_member_api_docs: false  # Set to true for API documentation requirements
