version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Say hello
          command: python app.py

workflows:
  hello-workflow:
    jobs:
      - build