# Enterprise Monitoring and Alerting Configuration for CircleCI

# Quality Gates Configuration
quality_gates:
  code_coverage:
    minimum_percentage: 80
    fail_build_on_decrease: true
  
  performance:
    max_build_time_minutes: 45
    max_test_time_minutes: 20
  
  security:
    max_critical_vulnerabilities: 0
    max_high_vulnerabilities: 2
  
  code_quality:
    max_code_smells: 10
    max_technical_debt_hours: 2

# Notification Channels
notifications:
  slack:
    channels:
      - name: "development"
        webhook: "${SLACK_WEBHOOK_DEV}"
        events: ["build_failed", "security_issues"]
      - name: "releases"
        webhook: "${SLACK_WEBHOOK_RELEASES}"
        events: ["deployment_success", "deployment_failed"]
      - name: "alerts"
        webhook: "${SLACK_WEBHOOK_ALERTS}"
        events: ["quality_gate_failed", "security_critical"]
  
  email:
    recipients:
      - "dev-team@enterprise-app.com"
      - "security-team@enterprise-app.com"
    events: ["security_critical", "build_failed"]
  
  jira:
    project_key: "ENTAPP"
    issue_type: "Bug"
    create_on: ["security_critical", "quality_gate_failed"]

# Metrics Collection
metrics:
  build_metrics:
    - name: "build_duration"
      type: "duration"
      unit: "seconds"
    - name: "test_count"
      type: "counter"
    - name: "test_success_rate"
      type: "percentage"
    - name: "artifact_size"
      type: "size"
      unit: "MB"
  
  quality_metrics:
    - name: "code_coverage"
      type: "percentage"
      source: "coverage/lcov.info"
    - name: "cyclomatic_complexity"
      type: "score"
      source: "analysis_results.json"
    - name: "maintainability_index"
      type: "score"
      source: "analysis_results.json"
  
  security_metrics:
    - name: "vulnerability_count"
      type: "counter"
      source: "security_report.json"
    - name: "dependency_count"
      type: "counter"
      source: "dependencies.json"

# Dashboards Configuration
dashboards:
  - name: "Build Overview"
    widgets:
      - type: "build_success_rate"
        timeframe: "30d"
      - type: "build_duration_trend"
        timeframe: "7d"
      - type: "test_coverage_trend"
        timeframe: "30d"
  
  - name: "Security Dashboard"
    widgets:
      - type: "vulnerability_summary"
        timeframe: "current"
      - type: "dependency_status"
        timeframe: "current"
      - type: "security_scan_history"
        timeframe: "90d"
  
  - name: "Quality Metrics"
    widgets:
      - type: "code_quality_score"
        timeframe: "current"
      - type: "technical_debt_trend"
        timeframe: "30d"
      - type: "test_stability"
        timeframe: "14d"

# Alerting Rules
alerts:
  - name: "Build Failure Rate High"
    condition: "build_failure_rate > 20% over 24h"
    severity: "warning"
    channels: ["slack:development"]
  
  - name: "Test Coverage Dropped"
    condition: "code_coverage < 80%"
    severity: "warning"
    channels: ["slack:development"]
  
  - name: "Critical Security Vulnerability"
    condition: "critical_vulnerabilities > 0"
    severity: "critical"
    channels: ["slack:alerts", "email", "jira"]
  
  - name: "Build Time Excessive"
    condition: "build_duration > 45min"
    severity: "warning"
    channels: ["slack:development"]
  
  - name: "Deployment Failed"
    condition: "deployment_status == 'failed'"
    severity: "high"
    channels: ["slack:releases", "email"]

# Reporting Schedule
reports:
  daily:
    - name: "Build Summary"
      template: "daily_build_summary"
      recipients: ["dev-team@enterprise-app.com"]
      time: "09:00"
  
  weekly:
    - name: "Quality Report"
      template: "weekly_quality_report"
      recipients: ["management@enterprise-app.com", "dev-team@enterprise-app.com"]
      time: "Monday 10:00"
  
  monthly:
    - name: "Security Assessment"
      template: "monthly_security_report"
      recipients: ["security-team@enterprise-app.com", "management@enterprise-app.com"]
      time: "1st Monday 14:00"

# Integration Settings
integrations:
  sonarqube:
    enabled: true
    url: "${SONARQUBE_URL}"
    token: "${SONARQUBE_TOKEN}"
    project_key: "enterprise-flutter-app"
  
  codecov:
    enabled: true
    token: "${CODECOV_TOKEN}"
    fail_threshold: 80
  
  snyk:
    enabled: true
    token: "${SNYK_TOKEN}"
    monitor: true
    fail_on: "high"
  
  jira:
    enabled: true
    url: "${JIRA_URL}"
    username: "${JIRA_USERNAME}"
    api_token: "${JIRA_API_TOKEN}"